apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-deploy
  template:
    metadata:
      labels:
        app: users-deploy
    spec:
      containers:
        - name: users-deploy
          image: stepigor/ofusers:arm
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: APP_PORT
            - name: PSWD_HASH_ROUNDS
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: PSWD_HASH_ROUNDS
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
            - name: REDIS_PSWD
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PSWD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: POSTGRES_HOST
            - name: POSTGRES_NAME
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: POSTGRES_NAME
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: POSTGRES_PORT
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PSWD
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PSWD
            - name: ACCESS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: ACCESS_JWT_SECRET
            - name: REFRESH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: REFRESH_JWT_SECRET
            - name: POSTGRES_PSWD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: POSTGRES_PSWD
